<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_QECapstone</name>
   <tag></tag>
   <elementGuidId>fba6f4e1-b027-437d-a034-8f5ec316c529</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>24206549-bc25-42f9-8f84-0a972a958b3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>px-4 py-2 text-center</value>
      <webElementGuid>dbad7d28-aa76-413a-8c97-d03ce742d932</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>QECapstone</value>
      <webElementGuid>7f1991b2-e200-48fe-a640-dedec7f93a98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;scroll-smooth&quot;]/body[@class=&quot;__className_8299a1&quot;]/div[@class=&quot;ml-96 p-5&quot;]/main[@class=&quot;space-y-5&quot;]/section[@class=&quot;overflow-hidden rounded-lg border border-N2&quot;]/div[@class=&quot;max-h-[60vh] min-h-[60vh] overflow-scroll&quot;]/table[@class=&quot;h-full w-full&quot;]/tbody[1]/tr[@class=&quot;bg-N1&quot;]/td[@class=&quot;px-4 py-2 text-center&quot;]</value>
      <webElementGuid>fbc48bea-5b90-4949-a560-d1bcb7940c29</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]</value>
      <webElementGuid>aa395987-9a30-48e2-99f7-0738e00c40a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'QECapstone' or . = 'QECapstone')]</value>
      <webElementGuid>aa58b677-7ad5-42ce-a6d1-14496caacad6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
