<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Alvi_flex items-center justify-cente_d488e3</name>
   <tag></tag>
   <elementGuidId>8c2315dd-1774-4f24-9257-172e01785da6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e6128973-36c0-4a39-9379-19e1dc8a6560</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7ae97091-307b-4b45-8f56-36dfaeeea37f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex items-center justify-center rounded-xl border border-S1 bg-S1 text-S5 hover:border-S2 hover:bg-S2 active:scale-95 active:border-S3 active:bg-S3 p-1.5</value>
      <webElementGuid>b7fe7da8-ec14-45e3-9ff1-37a8dd624424</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;__className_a5ed60&quot;]/div[@class=&quot;ml-96 p-5&quot;]/main[@class=&quot;space-y-5&quot;]/section[@class=&quot;z-10 max-h-[60vh] min-h-[60vh] overflow-scroll rounded-lg border border-N2&quot;]/table[@class=&quot;h-full w-full&quot;]/tbody[1]/tr[@class=&quot;bg-N1&quot;]/td[@class=&quot;px-4 py-2 text-center&quot;]/div[@class=&quot;flex items-center justify-center&quot;]/span[1]/button[@class=&quot;flex items-center justify-center rounded-xl border border-S1 bg-S1 text-S5 hover:border-S2 hover:bg-S2 active:scale-95 active:border-S3 active:bg-S3 p-1.5&quot;]</value>
      <webElementGuid>707a38be-8925-4390-a828-ad6cd62021e3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[3]</value>
      <webElementGuid>4f1ab9eb-226a-41ef-b1cd-73e79f94aebf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/button</value>
      <webElementGuid>4a9f754e-2204-49cb-928c-2ac98c7556a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button']</value>
      <webElementGuid>c91668af-c4e3-48b0-9a21-ba15fa5f9846</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[9]</value>
      <webElementGuid>d6ee868e-44ca-4ef9-a2f3-50556605c684</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[5]/div/span/button</value>
      <webElementGuid>92822f58-8b90-44f1-bced-6587a806867c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[5]</value>
      <webElementGuid>90b044d6-3c48-4db1-95fc-43ba1d6bc8a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[5]/div/span/button</value>
      <webElementGuid>cda6e3d2-91da-4a7c-8e32-0c643ac8b85c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
