<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Number Phone_w-full rounded-lg bg-tra_79501f</name>
   <tag></tag>
   <elementGuidId>51d6a683-614a-4c5a-ad47-f2489d4b272f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='628521708457234']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>90162308-07a6-4016-8a25-a964c0b44151</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full rounded-lg bg-transparent outline-none</value>
      <webElementGuid>093697e7-7439-4830-ad04-a7deeaeab52e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>141c1ecf-bb5b-4724-bb6f-33ff1253a9a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>628521708457234</value>
      <webElementGuid>9f1434fd-6490-4325-b64a-691e287a68ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;__className_a5ed60&quot;]/div[@class=&quot;ml-96 p-5&quot;]/main[@class=&quot;space-y-5&quot;]/section[@class=&quot;fixed -inset-5 z-50 flex items-center justify-center bg-black/50&quot;]/div[@class=&quot;w-2/5 rounded-xl bg-N1 p-8&quot;]/div[@class=&quot;rounded-xl border border-N2 p-8&quot;]/div[@class=&quot;flex flex-col gap-10&quot;]/div[@class=&quot;flex flex-col gap-8&quot;]/div[@class=&quot;flex flex-col gap-2&quot;]/section[1]/div[@class=&quot;group w-full rounded-xl border px-2 py-1 border-N2 text-N7 focus-within:border-P6 focus-within:text-P6 hover:border-P6 hover:text-P6 focus-within:hover:bg-transparent focus-within:hover:text-P6 h-[50px]&quot;]/div[@class=&quot;flex h-full w-full items-center justify-center gap-2&quot;]/div[@class=&quot;relative flex w-full flex-col justify-center&quot;]/input[@class=&quot;w-full rounded-lg bg-transparent outline-none&quot;]</value>
      <webElementGuid>f66585c5-c5c5-4820-b6f2-f508f4a18ad5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='628521708457234']</value>
      <webElementGuid>f9102649-e28d-4228-89e8-e6099dd49668</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/section/div/div/div/input</value>
      <webElementGuid>5e8eca4b-aab5-498d-a3b2-e227f0ecfcf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>0cd76763-b1b1-4804-a397-bb83289343d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='62855425775200']</value>
      <webElementGuid>81cc7643-adc5-44ec-a5f2-3e347d128c42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='6285217084574']</value>
      <webElementGuid>9ce57eaa-ac70-4434-a622-ad587663114f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
