<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Report</name>
   <tag></tag>
   <elementGuidId>a2e07544-db3a-411f-a6c6-0e854f3cce4d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Report')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>05d1f399-0b7e-4831-ba1b-e5c206492b81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex items-center gap-4</value>
      <webElementGuid>08639dae-67f6-4370-ac13-446efe27a31a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/report</value>
      <webElementGuid>a985e907-5561-4cdf-818d-39aa9688bad4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Report</value>
      <webElementGuid>004b5f5e-eb7d-479c-b676-41ddd1ef17d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;scroll-smooth&quot;]/body[@class=&quot;__className_8299a1&quot;]/nav[@class=&quot;fixed left-0 top-0 flex h-screen w-96 flex-col gap-14 border-r bg-N1.1 px-6 py-14 text-N3&quot;]/section[2]/ul[@class=&quot;flex w-full flex-col gap-4 text-xl font-semibold&quot;]/li[@class=&quot;w-full cursor-pointer rounded-lg p-4 hover:bg-P2 hover:text-P6 active:scale-95&quot;]/a[@class=&quot;flex items-center gap-4&quot;]</value>
      <webElementGuid>69d61fe0-97b8-4553-97dd-bbbfc4e5dd93</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Report')]</value>
      <webElementGuid>747e12ab-f673-4c5f-8e46-7fa7c122bdde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/report')]</value>
      <webElementGuid>5306d732-5b9d-42d5-8a1c-75f99606b2a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/a</value>
      <webElementGuid>44fdd9ed-54ee-46fe-ae42-0b398aa812eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/report' and (text() = 'Report' or . = 'Report')]</value>
      <webElementGuid>d0064762-eccd-4499-a9a3-9b1af92b8ff2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
