<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Membership</name>
   <tag></tag>
   <elementGuidId>f5a4e2b8-401e-4a35-8e8f-4a41a717490b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Membership')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f94acf64-4ae3-4372-9a40-fb2d8b16731f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex items-center gap-4</value>
      <webElementGuid>d9c10bda-8d00-4188-8e85-da46ec9bc4df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/membership</value>
      <webElementGuid>6783bb77-69ec-462e-b108-f0ce19df6a29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Membership</value>
      <webElementGuid>a6042c88-2979-460e-8d5d-480b9fdb0bcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;__className_a5ed60&quot;]/nav[@class=&quot;fixed left-0 top-0 flex h-screen w-96 flex-col gap-14 border-r bg-N1.1 px-6 py-14 text-N3&quot;]/section[2]/ul[@class=&quot;flex w-full flex-col gap-4 text-xl font-semibold&quot;]/li[@class=&quot;w-full cursor-pointer rounded-lg p-4 hover:bg-P2 hover:text-P6 active:scale-95&quot;]/a[@class=&quot;flex items-center gap-4&quot;]</value>
      <webElementGuid>cb24d0b2-54ca-48ad-ac67-f8882519b99f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Membership')]</value>
      <webElementGuid>e310d4c0-a566-41a0-b0f8-7d21a9a67b53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/membership')]</value>
      <webElementGuid>8a75b3eb-1dbc-4ecf-abf3-86680e5cac80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/a</value>
      <webElementGuid>b81be532-86c2-46af-97c8-22ff12e1d1ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/membership' and (text() = 'Membership' or . = 'Membership')]</value>
      <webElementGuid>de1a8d64-a5f0-4205-9a2a-e62d39d6cdc8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
