<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_LARGE_flex items-center justify-cent_bdf184</name>
   <tag></tag>
   <elementGuidId>ab1992ad-a063-4432-8dcc-6ce090edf40b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c4e0a7fe-bb6e-4560-bc6f-3c1955f30178</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>bc037f89-4ec8-4bd1-85e1-04a0c05efde6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex items-center justify-center rounded-xl border border-S1 bg-S1 text-S5 hover:border-S2 hover:bg-S2 active:scale-95 active:border-S3 active:bg-S3 p-1.5</value>
      <webElementGuid>d6b35db1-d919-4f05-8a82-61e5b083edf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;scroll-smooth&quot;]/body[@class=&quot;__className_8299a1&quot;]/div[@class=&quot;ml-96 p-5&quot;]/main[1]/div[@class=&quot;space-y-5&quot;]/section[@class=&quot;overflow-hidden rounded-lg border border-N2&quot;]/div[@class=&quot;max-h-[60vh] min-h-[60vh] overflow-scroll&quot;]/table[@class=&quot;h-full w-full&quot;]/tbody[1]/tr[@class=&quot;bg-N1&quot;]/td[@class=&quot;flex h-full items-center justify-center gap-2 px-4 py-2&quot;]/button[@class=&quot;flex items-center justify-center rounded-xl border border-S1 bg-S1 text-S5 hover:border-S2 hover:bg-S2 active:scale-95 active:border-S3 active:bg-S3 p-1.5&quot;]</value>
      <webElementGuid>977adb45-a43a-48e4-954d-c0779e33741e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[3]</value>
      <webElementGuid>dbd59c89-28bd-4f56-bd2d-6443b33aeba2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[8]/button</value>
      <webElementGuid>aecf23b2-77f7-426b-b422-88f38ca9ef4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button']</value>
      <webElementGuid>f61fde35-b610-4423-b53c-14de50ff8d18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[4]</value>
      <webElementGuid>94325022-aa9a-4f61-a81c-59c76cfa7fc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>5de0978c-5ed2-42c4-8ba1-63a82ddeaf95</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
