<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Delete</name>
   <tag></tag>
   <elementGuidId>8fb84174-5326-4df6-8c21-7c0ae8a8eb8d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5db70ed9-cb86-4fdd-a168-6b9211b14dee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>10bab07d-e6bc-44eb-8f5c-0b8991e09be9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mt-auto text-end active:scale-95 text-E4 hover:text-E5 text-sm</value>
      <webElementGuid>fb2ad5d9-8b47-4c1b-b047-9b0bc0acc752</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Delete</value>
      <webElementGuid>1b466862-cc0d-4e4c-ae67-3dc2e1e59bd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;scroll-smooth&quot;]/body[@class=&quot;__className_8299a1&quot;]/div[@class=&quot;ml-96 p-5&quot;]/main[1]/section[@class=&quot;fixed inset-0 top-10 z-50 flex justify-center&quot;]/section[@class=&quot;rounded-md pl-[6px] border-E4 bg-E4 h-[70px] w-[410px] border&quot;]/div[@class=&quot;flex h-full w-full gap-x-2 rounded-md bg-N1 px-2 py-1&quot;]/div[@class=&quot;flex flex-col items-end&quot;]/button[@class=&quot;mt-auto text-end active:scale-95 text-E4 hover:text-E5 text-sm&quot;]</value>
      <webElementGuid>33a90130-a84f-49e3-b46a-8ceeb012846e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[4]</value>
      <webElementGuid>86872c76-c7d2-4086-8d94-35c1d0f9d6fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>10482323-1322-4ddc-a7a1-794691f3e2e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Delete' or . = 'Delete')]</value>
      <webElementGuid>04afe1d6-a5a2-44bb-9259-e455802d454f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
