<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_NORMAL_beforecontent peer form-checkb_2fd3b5</name>
   <tag></tag>
   <elementGuidId>2bf58042-c585-44bd-832a-076ab51d6fb0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='checkbox'])[5]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bf1c8fdc-0396-4eb0-bcb4-9edb7313da11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>before:content[''] peer form-checkbox relative h-5 w-5 appearance-none rounded border before:absolute before:left-2/4 before:top-2/4 before:block before:h-12 before:w-12 before:-translate-x-2/4 before:-translate-y-2/4 before:rounded-full before:bg-P2 before:opacity-0 before:transition-opacity focus:outline-none focus:ring-0 cursor-default border-P4 text-P4 hover:before:opacity-20</value>
      <webElementGuid>2873c67e-76a7-4077-9701-32707cacee2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>e0ec17ac-c997-4ee6-88d6-e6147902331f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;scroll-smooth&quot;]/body[@class=&quot;__className_8299a1&quot;]/div[@class=&quot;ml-96 p-5&quot;]/main[1]/div[@class=&quot;space-y-5&quot;]/section[@class=&quot;overflow-hidden rounded-lg border border-N2&quot;]/div[@class=&quot;max-h-[60vh] min-h-[60vh] overflow-scroll&quot;]/table[@class=&quot;h-full w-full&quot;]/tbody[1]/tr[@class=&quot;bg-N1&quot;]/td[@class=&quot;px-4 py-2 text-center&quot;]/div[@class=&quot;flex items-center justify-center&quot;]/label[1]/input[@class=&quot;before:content[''] peer form-checkbox relative h-5 w-5 appearance-none rounded border before:absolute before:left-2/4 before:top-2/4 before:block before:h-12 before:w-12 before:-translate-x-2/4 before:-translate-y-2/4 before:rounded-full before:bg-P2 before:opacity-0 before:transition-opacity focus:outline-none focus:ring-0 cursor-default border-P4 text-P4 hover:before:opacity-20&quot;]</value>
      <webElementGuid>789a26a7-b5f7-408d-a25b-98fbaa192994</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='checkbox'])[5]</value>
      <webElementGuid>650d4a7d-0d1b-4fea-9790-c0ba4ffbdb6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td/div/label/input</value>
      <webElementGuid>6d80258d-53c5-455a-b9be-0f0c018c1ae7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox']</value>
      <webElementGuid>3a4355d2-b7ef-4bc2-a67e-0f86ec5dd3e0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
