<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Ingredient_ingredient</name>
   <tag></tag>
   <elementGuidId>0a17930c-e2a4-4827-86c0-f8f474c4be01</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ingredient']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ingredient</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0fca6684-16d4-482c-8f5f-ba2ebca666b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ingredient</value>
      <webElementGuid>0eefca09-28c6-457a-8dcb-d5247ee3eae1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full rounded-lg bg-transparent outline-none</value>
      <webElementGuid>6ee5c65d-edaa-4556-8497-57e06ef72481</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ba7f62e8-f001-4b1b-95b7-7c97146fd0dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>e</value>
      <webElementGuid>b91552ad-6b59-475a-85f7-b8269b1b10e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ingredient</value>
      <webElementGuid>14898b68-384b-46e2-9e45-f47b31ef5ee2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ingredient&quot;)</value>
      <webElementGuid>94ea8044-ac9c-45ab-80b6-6f8f90dfeb74</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ingredient']</value>
      <webElementGuid>64436836-33a5-415f-ae94-42637bd0d66c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[3]/div/div/div/input</value>
      <webElementGuid>5a8608a5-91aa-45c8-a181-d132e5f4ac71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ingredient' and @type = 'text' and @name = 'ingredient']</value>
      <webElementGuid>dcd59fea-3901-42ee-b6cf-b0be4e3b54fb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
