<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Membership</name>
   <tag></tag>
   <elementGuidId>0cfa97db-3465-43bc-a1ea-578c2624f9f7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>51678c5b-c9dd-4ad4-ad8b-706e31b6c654</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full cursor-pointer rounded-lg p-4 hover:bg-P2 hover:text-P6 active:scale-95</value>
      <webElementGuid>1fa3cd1d-ad72-47da-898d-c769fa3c9a5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Membership</value>
      <webElementGuid>9027190d-fad0-4666-9d75-e9f4c3af877d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;__className_a5ed60&quot;]/nav[@class=&quot;fixed left-0 top-0 flex h-screen w-96 flex-col gap-14 border-r bg-N1.1 px-6 py-14 text-N3&quot;]/section[2]/ul[@class=&quot;flex w-full flex-col gap-4 text-xl font-semibold&quot;]/li[@class=&quot;w-full cursor-pointer rounded-lg p-4 hover:bg-P2 hover:text-P6 active:scale-95&quot;]</value>
      <webElementGuid>25540da6-e1e6-4382-876a-0fa85d048852</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]</value>
      <webElementGuid>1c262f5c-b644-41d8-b125-456827ed948e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Membership' or . = 'Membership')]</value>
      <webElementGuid>2b57ef27-1716-4a4b-aaca-04e321df5758</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
